### ISSUE TITLE
example for mixin as discussed

### ISSUE THREAD

**Issue by pixelass** [Palmaswell/suit.less#1]
I forked your repo and implemented a mixin that handles a few things
- uppercase first letter of component
- lowercase first letter of modifier, descendant or state...
- allow setting a namespace
- set modifier
- set descendant
- set state
- ...

We discussed this in person and I thought you might be interested in this pure Less version instead of using inline JavaScript.

https://github.com/pixelass/suitless

**Comment by Palmaswell** [comment]
Thanks pixelass,

Always glad for improvement possibilities.
I already have a namespace, set modifier, decedent and state.
I have to consider if it is meaningful for the mixin to modify the classes according to the convention pascalcase, camelcase and so on. 

It is important that the mixin remains simple and understandable.

What do you think?

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
